#! /usr/bin/env bash

set -eo pipefail

unset HISTFILE
export RESTIC_REPOSITORY="s3:https://s3.wasabisys.com/holo-hydra-backup"
export AWS_ACCESS_KEY_ID="***"
export AWS_SECRET_ACCESS_KEY="***"
export RESTIC_PASSWORD="***"
restic init
pg_dump -U hydra hydra --clean | restic backup --stdin --stdin-filename hydra-master.bak

echo "Hydra backup created and uploaded to wasabi successfully"
